[book]
language = "en"
multilingual = false
src = "src"
title = "nix-shell-parts"

[output.html]
git-repository-url = "https://github.com/ergon/nix-shell-parts"
edit-url-template = "https://github.com/ergon/nix-shell-parts/edit/main/docs/{path}"